apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfe-app
  template:
    metadata:
      labels:
        app: pfe-app
    spec:
      containers:
      - name: pfe-app
        image: sirine811/pfe-sample-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
